### ISSUE TITLE
Unable to load DLL 'mkl_rt.dll'

### ISSUE THREAD

**Issue by PhilPJL** [MKL-NET/MKL.NET#15]
Hi, 

I'm probably missing something obvious but for example `MKLNET.Vml.Asin(Values, Result1);` results in:

> System.DllNotFoundException
>   HResult=0x80131524
>   Message=Unable to load DLL 'mkl_rt.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
>   Source=MKL.NET
>   StackTrace:
>    at MKLNET.Vml.vdAsin(Int32 n, Double[] a, Double[] r)
>    at MKLNET.Vml.Asin(Double[] a, Double[] r)
> 

I've add MKL.NET + Matrix + Optimization + Statistics and the only native dependency seems to be MKL.NET.Native.dll.
Should mkl_rt.dll be distributed with your package or is it something I have to install separately?

**Comment by PhilPJL** [comment]
Oops. Just needed to reference the "required runtime packages" :)
